Integration tests on Iron
UniversalRobots/Universal_Robots_ROS2_Ignition_Simulation pull request #47
Opened 2024-08-26 14:08 UTC by VinDp

This PR is a manual backport of #17, since: 

- some lines from the `ros2` branch were missing in the `iron` branch
- the `test_description.py` was searching for urdfs that do not exist in this branch of the repo, since the description refactoring only happened on rolling

With these minimal changes both tests (gz and description) seem to work.

2024-09-02 10:31 UTC, fmauch requested changes

2024-09-02 10:31 UTC, fmauch commented on ur_simulation_gz/test/test_description.py
The test_description script doesn't make too much sense here, in my opinion. For Iron we don't have a custom description in this repo.

2024-09-02 10:31 UTC, fmauch commented on ur_simulation_gz/package.xml
> +  <test_depend>xacro</test_depend>
Probably not needed when the test_description test is removed.

2024-09-02 10:31 UTC, fmauch commented on ur_simulation_gz/CMakeLists.txt
> +  ament_add_pytest_test(description test/test_description.py)
This could be removed with the test altogether.

2024-09-02 11:31 UTC, VinDp commented on ur_simulation_gz/test/test_description.py
Yeah, it makes sense. I will remove it.

2024-09-03 10:30 UTC, fmauch approved these changes

2024-09-03 10:30 UTC, merged

2024-09-04 12:38 UTC, VinDp commented
@Mergifyio backport humble